<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Cryptography.Fernet" Version="1.1.1" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="FluentIcons.Avalonia" Version="2.0.320" />
    <PackageReference Include="MeiliSearch" Version="0.18.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Views\All_EntriesPageView.axaml.cs">
      <DependentUpon>All_EntriesPageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SecurityPageView.axaml.cs">
      <DependentUpon>SecurityPageView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
	
  <ItemGroup>
    <Folder Include="DataBase\" />
  </ItemGroup>
</Project>
